# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCMockDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OCMockDemo

  target 'OCMockDemoTests' do
    inherit! :search_paths
    pod 'OCMock'
    # Pods for testing
  end

  target 'OCMockDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
